### ISSUE TITLE
Setup Project/Directory Structure

### ISSUE THREAD

**Issue by avazzano7** [mmehta2669/Final_Project_Group_2#1]
## Due Date
9/25/2024

## Description
Initialize the main project directory with appropriate file names. Ensure the directory structure is consistent with best practices for Python.

Define the basic class structure that will be used in this project. Create initial classes (attributes not yet written out).

## Acceptance Criteria
- project directory and subdirectories are created as per specified structure.
- essential files (README.md, .gitignore) are added to the project root.
- initial classes are created.

**Comment by Marcus-Snell** [comment]
Completed on 9/25/2024.
