### ISSUE TITLE
Implement Lives System

### ISSUE THREAD

**Issue by avazzano7** [mmehta2669/Final_Project_Group_2#10]
## Due Date
11/05/2024

## Description
Display 3 Lives on the top of the game screen. For each collision, the player will lose a life.

## Acceptance Criteria
- 3 Lives will be displayed on the top of the game screen
- For each collision, one life will be lost
- If there are no lives left, the game will end. (this does not require a game over screen, the game can simply exit for this issue)

**Comment by Marcus-Snell** [comment]
Three ship icons added to screen to represent lives available.  When a collision is detected with an asteroid and the player character, one of the ship icons is removed and the player is reset to the center of the screen.  When all three icons have been removed, the game ends.
