### ISSUE TITLE
Asteroid Travel Path

### ISSUE THREAD

**Issue by avazzano7** [mmehta2669/Final_Project_Group_2#15]
## Due Date
12/03/2024

## Description
Asteroids will move in random directions across the screen, adding unpredictability and enhancing gameplay dynamics.

## Acceptance Criteria
- Asteroids no longer only move horizontally.
- The path of asteroid travel will be randomized at the time of spawn.
- The path of asteroid travel will remain constant for each asteroid after spawn but may vary in angle or speed between different asteroids.
- Randomized paths will ensure no two asteroids share identical trajectories.

**Comment by Marcus-Snell** [comment]
Speed, angle, and randomization applied as defined.
