### ISSUE TITLE
Pause Functionality with 'P' Key

### ISSUE THREAD

**Issue by avazzano7** [mmehta2669/Final_Project_Group_2#17]
## Due Date
12/03/2024

## Description
The game currently lacks the ability to pause, which impacts the user experience when a player needs to temporarily halt the gameplay. Allowing the user to press the 'P' key to pause/un-pause the game will give players more control during gameplay.

## Acceptance Criteria
- Pressing the 'P' key shall pause all in-game activity, including animations and timers.
- Pressing the 'P' key while in a paused state shall resume the game.
- A visual indicator (e.g., "Game Paused") shall be displayed when the game is paused.

**Comment by mmehta2669** [comment]
Adding Pause function but I had a different implementation then the proposed, added full menu with a resume button and a quit button that opens on pressing esc
