### ISSUE TITLE
Implement Basic Game Loop

### ISSUE THREAD

**Issue by tyrekblanks** [mmehta2669/Final_Project_Group_2#2]
## Due Date
10/08/2024

## Description
As a player, the basic game loop involves frames updating over an interval to be displayed. The frame rate chosen will produce smooth movements in graphics. Lives, spaceship, and asteroids display on the screen and update on every frame refresh.

## Acceptance Criteria
- Lives, spaceship, and asteroids appear on screen
- Game updates with each frame refresh
- Smooth frame rate

**Comment by avazzano7** [comment]
issue closed, and lives moved to separate issue
